excluded:
    - ToDoList/AppDelegate.swift
    - ToDoList/SceneDelegate.swift
    - Pods
    - ToDoListTests
    - ToDoListUITests
    - ToDoList/Models/DataModel.swift
disabled_rules:
    - large_tuple
warning_threshold: 1
